(function() {
  var OPTIONS, TRM, TYPES, alert, app_info, badge, debug, echo, email, email_options, help, info, log, njs_path, nodemailer, rpr, send_email, warn, whisper;

  njs_path = require('path');

  OPTIONS = require('coffeenode-options');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'USERDB/core';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  app_info = OPTIONS.get_app_info();

  nodemailer = require('nodemailer');

  email_options = require(njs_path.join(app_info['user-home'], 'coffeenode-mail-options.json'));

  send_email = function(email) {
    var smtpTransport;
    info("sending mail...");
    smtpTransport = nodemailer.createTransport('SMTP', email_options);
    return smtpTransport.sendMail(email, function(error, response) {
      if (error != null) {
        warn(error);
      } else {
        info("Message sent: " + response.message);
      }
      return smtpTransport.close();
    });
  };

  email = {
    from: "Node Mailer <wolfgang.lipp@gmail.com>",
    to: "Your Name <paragate@gmx.net>",
    subject: "Hello ✔",
    text: "Hello world 𪜃"
  };

}).call(this);
/****generated by https://github.com/loveencounterflow/larq****/