// Generated by CoffeeScript 1.6.3
(function() {
  var TRM, TYPES, USERDB, alert, badge, debug, echo, help, info, log, mixins, njs_fs, njs_path, njs_url, njs_util, rpr, warn, whisper;

  njs_util = require('util');

  njs_path = require('path');

  njs_fs = require('fs');

  njs_url = require('url');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'USERDB/main';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  mixins = [require('./core'), require('./users'), require('./passwords'), require('./dump'), require('./integrity')];

  USERDB = this;

  (function() {
    var mixin, name, value, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = mixins.length; _i < _len; _i++) {
      mixin = mixins[_i];
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (name in mixin) {
          value = mixin[name];
          if (USERDB[name] != null) {
            throw new Error("name clash: " + (rpr(name)));
          }
          _results1.push(USERDB[name] = value);
        }
        return _results1;
      })());
    }
    return _results;
  })();

}).call(this);
