// Generated by CoffeeScript 1.6.3
/* TAINT experimental — do not use yet*/


(function() {
  var LANGUAGE, TRM, echo, log, name_, rpr, teacup;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  log = TRM.log.bind(TRM);

  echo = TRM.echo.bind(TRM);

  LANGUAGE = require('./LANGUAGE');

  /* https://github.com/goodeggs/teacup*/


  teacup = require('teacup');

  for (name_ in teacup) {
    eval("" + (name_.toUpperCase()) + " = teacup[ " + (rpr(name_)) + " ]");
  }

  this.login_get = RENDERABLE(function(O) {
    var _this = this;
    return FORM('#cnd-userdb-login-form', {
      method: 'post'
    }, function() {
      return DIV(function() {
        INPUT({
          name: 'uid',
          type: 'text'
        });
        INPUT({
          name: 'pwd',
          type: 'password'
        });
        return INPUT({
          type: 'submit'
        });
      });
    });
  });

  this.login_post = RENDERABLE(function(O) {});

}).call(this);
