
/* TAINT experimental — do not use yet */

(function() {
  var LANGUAGE, TRM, echo, log, name_, rpr, teacup;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  log = TRM.log.bind(TRM);

  echo = TRM.echo.bind(TRM);

  LANGUAGE = require('./LANGUAGE');


  /* https://github.com/goodeggs/teacup */

  teacup = require('teacup');

  for (name_ in teacup) {
    eval("" + (name_.toUpperCase()) + " = teacup[ " + (rpr(name_)) + " ]");
  }

  this.login_get = RENDERABLE(function(O) {
    return FORM('#cnd-userdb-login-form', {
      method: 'post'
    }, (function(_this) {
      return function() {
        return DIV(function() {
          INPUT({
            name: 'uid',
            type: 'text'
          });
          INPUT({
            name: 'pwd',
            type: 'password'
          });
          return INPUT({
            type: 'submit'
          });
        });
      };
    })(this));
  });

  this.login_post = RENDERABLE(function(O) {});

}).call(this);
/****generated by https://github.com/loveencounterflow/larq****/